### ISSUE TITLE
Using KDC Proxy without RD Gateway

### ISSUE THREAD

**Issue by andrewheberle** [Devolutions/MsRdpEx#75]
Reading through the Devolutions blog it sounds like it is possible to set "KDCProxyName" and "UserSpecifiedServerName" in rgw RDP connection file so we can leverage Kerberos outside of the local network so NLA will work correctly.

Is this correct?

I have the following options set in my RDP connection file that I'm using via "MsRdpEx.exe":

```
gatewayusagemethod:i:0
full address:s:localhost:PORT
KDCProxyName:s:kdc.example.com
UserSpecifiedServerName:s:real-hostname.internal.example.com
DisableUDPTransport:i:1
UseSSLSecurityLayer:i:1
```

This works fine when using username and password authentication, but also does not seem to use the KDC Proxy based on the logs there, while attempting to use smartcard based authentication fails NLA as the DC is not reachable (as expected).

The use of "localhost:PORT" above is we are using a tunnelling solution for external access from our Zero Trust provider.

**Comment by awakecoding** [comment]
Do you put more than just the hostname in the KDCProxyName? It has such an error prone format, and it's limited to 255 characters that I added KDCProxyURL in MsRdpEx: just put the https URL with port and path, no size limit.

You seem unsure that it is picking it up for password-based authentication, so maybe it's not even using Kerberos indeed. However, there are more things to check for smartcard authentication + Kerberos, because the error you're getting could still happen with a KDC line of sight, I've blogged about strict KDC validation here: https://awakecoding.com/posts/rdp-smartcard-logon-user-name-does-not-exist/

If the KDC proxy gets picked up, you'll see outgoing traffic from lsass.exe, that's something you can catch in ProcMon. Also, make sure that the WPAD service on your system is running, because yes, this will silently break the KDC proxy client in Windows: https://awakecoding.com/posts/disabling-web-proxy-auto-detect-wpad-correctly/

**Comment by andrewheberle** [comment]
When setting the “KDCProxyName” setting i wasn’t even seeing the connection attempt to use the proxy, but after setting the “KDCProxyURL” option the client actually used the proxy. 

That opened up a whole other set of issues unrelated to MsRdpEx as there were some problems with the KDC Proxy itself but now that’s resolved everything seems to work as expected. 

Thanks for the help.
